const {Pool}=require('pg');const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL}):null;async function dbinit(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS projects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,description text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());CREATE TABLE IF NOT EXISTS analyses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid REFERENCES projects(id) ON DELETE CASCADE,name text NOT NULL,query jsonb NOT NULL DEFAULT '{}'::jsonb,search_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,corpus jsonb NOT NULL DEFAULT '[]'::jsonb,ref_coverage jsonb NOT NULL DEFAULT '{}'::jsonb,parameters jsonb NOT NULL DEFAULT '{}'::jsonb,network jsonb NOT NULL DEFAULT '{}'::jsonb,cited_works jsonb NOT NULL DEFAULT '{}'::jsonb,view_state jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());CREATE INDEX IF NOT EXISTS analyses_project_idx ON analyses(project_id,updated_at DESC);`)}dbinit().catch(console.error);
const http=require('http'),fs=require('fs'),path=require('path'),https=require('https'),url=require('url');const root=path.join(__dirname,'public');
function send(r,s,t,d){r.writeHead(s,{'Content-Type':t,'Access-Control-Allow-Origin':'*'});r.end(d)}
function getJSON(target){return new Promise((ok,no)=>{let headers={'User-Agent':'BiblioMap/1.0'};if(process.env.OPENALEX_API_KEY)headers.Authorization='Bearer '+process.env.OPENALEX_API_KEY;https.get(target,{headers},x=>{let d='';x.on('data',c=>d+=c);x.on('end',()=>{try{x.statusCode>=400?no(Error('OpenAlex '+x.statusCode+': '+d.slice(0,160))):ok(JSON.parse(d))}catch(e){no(e)}})}).on('error',no)})}
async function search(q,max){let out=[],cursor='*',meta=null;max=Math.min(Math.max(+max||500,25),10000);while(out.length<max){let n=Math.min(100,max-out.length),p=new URLSearchParams({search:q,filter:'type:article|review',per_page:String(n),cursor,select:'id,doi,display_name,publication_year,cited_by_count,authorships,primary_location,topics,open_access,referenced_works'});let j=await getJSON('https://api.openalex.org/works?'+p);meta=meta||j.meta;out.push(...j.results);if(!j.meta.next_cursor||!j.results.length)break;cursor=j.meta.next_cursor}return {meta:{...meta,retrieved:out.length},results:out}}
async function refs(ids){let out=[];for(let i=0;i<ids.length;i+=100){let batch=ids.slice(i,i+100).map(x=>x.split('/').pop()).join('|');let p=new URLSearchParams({filter:'openalex:'+batch,per_page:'100',select:'id,display_name,publication_year,cited_by_count,authorships,primary_location,topics'});let j=await getJSON('https://api.openalex.org/works?'+p);out.push(...j.results)}return out}
http.createServer(async(q,r)=>{let u=url.parse(q.url,true);try{
if(u.pathname==='/api/projects'&&q.method==='GET'){let x=await pool.query("SELECT p.*,count(a.id)::int analysis_count FROM projects p LEFT JOIN analyses a ON a.project_id=p.id GROUP BY p.id ORDER BY p.updated_at DESC");return send(r,200,'application/json',JSON.stringify({projects:x.rows}))}
if(u.pathname==='/api/projects'&&q.method==='POST'){let body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),x=await pool.query("INSERT INTO projects(name,description) VALUES($1,$2) RETURNING *",[b.name||'Untitled project',b.description||null]);return send(r,201,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname==='/api/analyses'&&q.method==='GET'){let x=await pool.query("SELECT id,project_id,name,query,parameters,view_state,created_at,updated_at,jsonb_array_length(corpus) corpus_count FROM analyses WHERE ($1::uuid IS NULL OR project_id=$1) ORDER BY updated_at DESC",[u.query.project_id||null]);return send(r,200,'application/json',JSON.stringify({analyses:x.rows}))}
if(u.pathname==='/api/analyses'&&q.method==='POST'){let body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}');let x=await pool.query("INSERT INTO analyses(project_id,name,query,search_snapshot,corpus,ref_coverage,parameters,network,cited_works,view_state) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,project_id,name,created_at",[b.project_id,b.name||'Analysis',b.query||{},b.search_snapshot||{},b.corpus||[],b.ref_coverage||{},b.parameters||{},b.network||{},b.cited_works||{},b.view_state||{}]);await pool.query("UPDATE projects SET updated_at=now() WHERE id=$1",[b.project_id]);return send(r,201,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname.startsWith('/api/analyses/')&&q.method==='GET'){let id=u.pathname.split('/').pop(),x=await pool.query("SELECT * FROM analyses WHERE id=$1",[id]);return x.rowCount?send(r,200,'application/json',JSON.stringify(x.rows[0])):send(r,404,'application/json','{"error":"Not found"}')}
if(u.pathname==='/api/search')return send(r,200,'application/json',JSON.stringify(await search(String(u.query.q||'leadership development'),u.query.max)));if(u.pathname==='/api/works'){let ids=String(u.query.ids||'').split(',').filter(Boolean).slice(0,1000);return send(r,200,'application/json',JSON.stringify({results:await refs(ids)}));}if(u.pathname==='/health')return send(r,200,'application/json','{"ok":true}');let p=path.join(root,u.pathname==='/'?'index.html':u.pathname.slice(1));fs.readFile(p,(e,d)=>e?send(r,404,'text/plain','Not found'):send(r,200,p.endsWith('.css')?'text/css':p.endsWith('.js')?'application/javascript':'text/html',d))}catch(e){send(r,500,'application/json',JSON.stringify({error:e.message}))}}).listen(process.env.PORT||3000);