import pg from 'pg';import {build as buildNetwork} from './analysis-engine.mjs';import http from 'http';import fs from 'fs';import path from 'path';import https from 'https';import url from 'url';import {fileURLToPath} from 'url';const {Pool}=pg;const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL}):null;
async function dbinit(){if(!pool)return;await pool.query(`
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS projects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,description text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS searches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid REFERENCES projects(id) ON DELETE CASCADE,name text NOT NULL,query jsonb NOT NULL DEFAULT '{}'::jsonb,result_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,result_count int NOT NULL DEFAULT 0,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corpora(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid REFERENCES projects(id) ON DELETE CASCADE,search_id uuid REFERENCES searches(id) ON DELETE SET NULL,name text NOT NULL,version int NOT NULL DEFAULT 1,works jsonb NOT NULL DEFAULT '[]'::jsonb,decisions jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS analyses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid REFERENCES projects(id) ON DELETE CASCADE,corpus_id uuid REFERENCES corpora(id) ON DELETE RESTRICT,name text NOT NULL,query jsonb NOT NULL DEFAULT '{}'::jsonb,search_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,corpus jsonb NOT NULL DEFAULT '[]'::jsonb,ref_coverage jsonb NOT NULL DEFAULT '{}'::jsonb,parameters jsonb NOT NULL DEFAULT '{}'::jsonb,network jsonb NOT NULL DEFAULT '{}'::jsonb,cited_works jsonb NOT NULL DEFAULT '{}'::jsonb,view_state jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
ALTER TABLE analyses ADD COLUMN IF NOT EXISTS corpus_id uuid REFERENCES corpora(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS searches_project_idx ON searches(project_id,updated_at DESC);CREATE INDEX IF NOT EXISTS corpora_project_idx ON corpora(project_id,updated_at DESC);CREATE INDEX IF NOT EXISTS analyses_project_idx ON analyses(project_id,updated_at DESC);`)}dbinit().catch(e=>console.error('DB migration failed',e));
const __dirname=path.dirname(fileURLToPath(import.meta.url));const root=path.join(__dirname,'public');
function send(r,s,t,d){r.writeHead(s,{'Content-Type':t,'Access-Control-Allow-Origin':'*'});r.end(d)}
function getJSON(target){return new Promise((ok,no)=>{let headers={'User-Agent':'BiblioMap/1.0'};if(process.env.OPENALEX_API_KEY)headers.Authorization='Bearer '+process.env.OPENALEX_API_KEY;https.get(target,{headers},x=>{let d='';x.on('data',c=>d+=c);x.on('end',()=>{try{x.statusCode>=400?no(Error('OpenAlex '+x.statusCode+': '+d.slice(0,160))):ok(JSON.parse(d))}catch(e){no(e)}})}).on('error',no)})}
async function search(q,max){let out=[],cursor='*',meta=null;max=Math.min(Math.max(+max||500,25),10000);while(out.length<max){let n=Math.min(100,max-out.length),p=new URLSearchParams({search:q,filter:'type:article|review',per_page:String(n),cursor,select:'id,doi,display_name,publication_year,cited_by_count,authorships,primary_location,topics,open_access,referenced_works'});let j=await getJSON('https://api.openalex.org/works?'+p);meta=meta||j.meta;out.push(...j.results);if(!j.meta.next_cursor||!j.results.length)break;cursor=j.meta.next_cursor}return {meta:{...meta,retrieved:out.length},results:out}}
async function refs(ids){let out=[];for(let i=0;i<ids.length;i+=100){let batch=ids.slice(i,i+100).map(x=>x.split('/').pop()).join('|');let p=new URLSearchParams({filter:'openalex:'+batch,per_page:'100',select:'id,display_name,publication_year,cited_by_count,authorships,primary_location,topics'});let j=await getJSON('https://api.openalex.org/works?'+p);out.push(...j.results)}return out}
http.createServer(async(q,r)=>{let u=url.parse(q.url,true);try{
if(u.pathname==='/api/db-integrity'&&q.method==='GET'){let counts=await pool.query("SELECT (SELECT count(*) FROM projects)::int projects,(SELECT count(*) FROM searches)::int searches,(SELECT count(*) FROM corpora)::int corpora,(SELECT count(*) FROM analyses)::int analyses");let ps=await pool.query("SELECT p.id,p.name,(SELECT count(*) FROM searches s WHERE s.project_id=p.id)::int searches,(SELECT count(*) FROM corpora c WHERE c.project_id=p.id)::int corpora,(SELECT count(*) FROM analyses a WHERE a.project_id=p.id)::int analyses FROM projects p ORDER BY p.created_at");let ss=await pool.query("SELECT id,project_id,name,result_count,jsonb_array_length(COALESCE(result_snapshot->'works','[]'::jsonb)) snapshot_count FROM searches ORDER BY created_at");let cs=await pool.query("SELECT id,project_id,search_id,name,version,jsonb_array_length(works) work_count FROM corpora ORDER BY created_at");let aa=await pool.query("SELECT id,project_id,corpus_id,name,jsonb_array_length(corpus) corpus_count,COALESCE(jsonb_array_length(network->'nodes'),0) node_count,COALESCE(jsonb_array_length(network->'edges'),0) edge_count,parameters,network->'stats' stats,(search_snapshot<>'{}'::jsonb) has_search_snapshot,(cited_works<>'{}'::jsonb) has_cited_works,(view_state<>'{}'::jsonb) has_view_state FROM analyses ORDER BY created_at");let orphan=await pool.query("SELECT (SELECT count(*) FROM searches s LEFT JOIN projects p ON p.id=s.project_id WHERE p.id IS NULL)::int orphan_searches,(SELECT count(*) FROM corpora c LEFT JOIN projects p ON p.id=c.project_id WHERE p.id IS NULL)::int orphan_corpora,(SELECT count(*) FROM analyses a LEFT JOIN projects p ON p.id=a.project_id WHERE p.id IS NULL)::int orphan_analyses,(SELECT count(*) FROM corpora c LEFT JOIN searches s ON s.id=c.search_id WHERE c.search_id IS NOT NULL AND s.id IS NULL)::int broken_corpus_search_links,(SELECT count(*) FROM analyses a LEFT JOIN corpora c ON c.id=a.corpus_id WHERE a.corpus_id IS NOT NULL AND c.id IS NULL)::int broken_analysis_corpus_links");return send(r,200,'application/json',JSON.stringify({counts:counts.rows[0],projects:ps.rows,searches:ss.rows,corpora:cs.rows,analyses:aa.rows,integrity:orphan.rows[0]}))}
if(u.pathname==='/api/compute'&&q.method==='POST'){let body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),opt={method:b.method||'co_citation',counting:b.counting||'full',normalization:b.normalization||'association_strength',minNode:b.min_node_occurrence??3,minRaw:b.min_raw_edge_count??2,resolution:b.resolution??0.02,seed:b.seed??42,restarts:b.restarts??10};let network=buildNetwork(b.corpus||[],opt);network.clustering=opt._cluster_meta||{};return send(r,200,'application/json',JSON.stringify({network,parameters:opt}))}

if(u.pathname==='/api/searches'&&q.method==='GET'){let x=await pool.query("SELECT id,project_id,name,query,result_count,created_at,updated_at FROM searches WHERE project_id=$1 ORDER BY updated_at DESC",[u.query.project_id]);return send(r,200,'application/json',JSON.stringify({searches:x.rows}))}
if(u.pathname.match(/^\/api\/searches\/[0-9a-f-]+$/)&&q.method==='GET'){let id=u.pathname.split('/').pop(),x=await pool.query("SELECT * FROM searches WHERE id=$1",[id]);return x.rowCount?send(r,200,'application/json',JSON.stringify(x.rows[0])):send(r,404,'application/json','{"error":"Not found"}')}
if(u.pathname==='/api/searches'&&q.method==='POST'){let body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),x=await pool.query("INSERT INTO searches(project_id,name,query,result_snapshot,result_count) VALUES($1,$2,$3,$4,$5) RETURNING *",[b.project_id,b.name||'Saved search',b.query||{},b.result_snapshot||{},b.result_count||0]);return send(r,201,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname.match(/^\/api\/searches\/[0-9a-f-]+$/)&&q.method==='PATCH'){let id=u.pathname.split('/').pop(),body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),x=await pool.query("UPDATE searches SET name=COALESCE($2,name),updated_at=now() WHERE id=$1 RETURNING *",[id,b.name]);return send(r,200,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname.match(/^\/api\/searches\/[0-9a-f-]+$/)&&q.method==='DELETE'){let id=u.pathname.split('/').pop();await pool.query("DELETE FROM searches WHERE id=$1",[id]);return send(r,200,'application/json','{"ok":true}')}
if(u.pathname==='/api/corpora'&&q.method==='GET'){let x=await pool.query("SELECT id,project_id,search_id,name,version,jsonb_array_length(works) work_count,created_at,updated_at FROM corpora WHERE project_id=$1 ORDER BY updated_at DESC",[u.query.project_id]);return send(r,200,'application/json',JSON.stringify({corpora:x.rows}))}
if(u.pathname==='/api/corpora'&&q.method==='POST'){let body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),x=await pool.query("INSERT INTO corpora(project_id,search_id,name,version,works,decisions) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[b.project_id,b.search_id||null,b.name||'Corpus',b.version||1,JSON.stringify(b.works||[]),b.decisions||{}]);return send(r,201,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname.match(/^\/api\/corpora\/[0-9a-f-]+$/)&&q.method==='GET'){let id=u.pathname.split('/').pop(),x=await pool.query("SELECT * FROM corpora WHERE id=$1",[id]);return x.rowCount?send(r,200,'application/json',JSON.stringify(x.rows[0])):send(r,404,'application/json','{"error":"Not found"}')}
if(u.pathname.match(/^\/api\/corpora\/[0-9a-f-]+$/)&&q.method==='PATCH'){let id=u.pathname.split('/').pop(),body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),x=await pool.query("UPDATE corpora SET name=COALESCE($2,name),updated_at=now() WHERE id=$1 RETURNING *",[id,b.name]);return send(r,200,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname.match(/^\/api\/corpora\/[0-9a-f-]+$/)&&q.method==='DELETE'){let id=u.pathname.split('/').pop();await pool.query("DELETE FROM corpora WHERE id=$1",[id]);return send(r,200,'application/json','{"ok":true}')}
if(u.pathname.match(/^\/api\/projects\/[0-9a-f-]+$/)&&q.method==='PATCH'){let id=u.pathname.split('/').pop(),body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),x=await pool.query("UPDATE projects SET name=COALESCE($2,name),description=COALESCE($3,description),updated_at=now() WHERE id=$1 RETURNING *",[id,b.name,b.description]);return send(r,200,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname.match(/^\/api\/projects\/[0-9a-f-]+$/)&&q.method==='DELETE'){let id=u.pathname.split('/').pop();await pool.query("DELETE FROM projects WHERE id=$1",[id]);return send(r,200,'application/json','{"ok":true}')}
if(u.pathname==='/api/projects'&&q.method==='GET'){let x=await pool.query("SELECT p.*,count(a.id)::int analysis_count FROM projects p LEFT JOIN analyses a ON a.project_id=p.id GROUP BY p.id ORDER BY p.updated_at DESC");return send(r,200,'application/json',JSON.stringify({projects:x.rows}))}
if(u.pathname==='/api/projects'&&q.method==='POST'){let body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),x=await pool.query("INSERT INTO projects(name,description) VALUES($1,$2) RETURNING *",[b.name||'Untitled project',b.description||null]);return send(r,201,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname==='/api/analyses'&&q.method==='GET'){let x=await pool.query("SELECT id,project_id,name,query,parameters,view_state,created_at,updated_at,jsonb_array_length(corpus) corpus_count FROM analyses WHERE ($1::uuid IS NULL OR project_id=$1) ORDER BY updated_at DESC",[u.query.project_id||null]);return send(r,200,'application/json',JSON.stringify({analyses:x.rows}))}
if(u.pathname==='/api/analyses'&&q.method==='POST'){let body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}');let x=await pool.query("INSERT INTO analyses(project_id,corpus_id,name,query,search_snapshot,corpus,ref_coverage,parameters,network,cited_works,view_state) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,project_id,name,created_at",[b.project_id,b.corpus_id||null,b.name||'Analysis',b.query||{},b.search_snapshot||{},JSON.stringify(b.corpus||[]),b.ref_coverage||{},b.parameters||{},b.network||{},b.cited_works||{},b.view_state||{}]);await pool.query("UPDATE projects SET updated_at=now() WHERE id=$1",[b.project_id]);return send(r,201,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname.match(/^\/api\/analyses\/[0-9a-f-]+$/)&&q.method==='PATCH'){let id=u.pathname.split('/').pop(),body='';for await(const ch of q)body+=ch;let b=JSON.parse(body||'{}'),x=await pool.query("UPDATE analyses SET name=COALESCE($2,name),view_state=COALESCE($3,view_state),updated_at=now() WHERE id=$1 RETURNING id,name,updated_at",[id,b.name,b.view_state]);return send(r,200,'application/json',JSON.stringify(x.rows[0]))}
if(u.pathname.match(/^\/api\/analyses\/[0-9a-f-]+$/)&&q.method==='DELETE'){let id=u.pathname.split('/').pop();await pool.query("DELETE FROM analyses WHERE id=$1",[id]);return send(r,200,'application/json','{"ok":true}')}
if(u.pathname.startsWith('/api/analyses/')&&q.method==='GET'){let id=u.pathname.split('/').pop(),x=await pool.query("SELECT * FROM analyses WHERE id=$1",[id]);return x.rowCount?send(r,200,'application/json',JSON.stringify(x.rows[0])):send(r,404,'application/json','{"error":"Not found"}')}
if(u.pathname==='/api/search-page'){let qq=String(u.query.q||''),cursor=String(u.query.cursor||'*'),n=Math.min(+u.query.per_page||100,100),p=new URLSearchParams({search:qq,filter:'type:article|review',per_page:String(n),cursor,select:'id,doi,display_name,publication_year,cited_by_count,authorships,primary_location,topics,open_access,referenced_works'});let j=await getJSON('https://api.openalex.org/works?'+p);return send(r,200,'application/json',JSON.stringify(j))}if(u.pathname==='/api/search')return send(r,200,'application/json',JSON.stringify(await search(String(u.query.q||'leadership development'),u.query.max)));if(u.pathname==='/api/works'){let ids=String(u.query.ids||'').split(',').filter(Boolean).slice(0,1000);return send(r,200,'application/json',JSON.stringify({results:await refs(ids)}));}if(u.pathname==='/health')return send(r,200,'application/json','{"ok":true}');let p=path.join(root,u.pathname==='/'?'index.html':u.pathname.slice(1));fs.readFile(p,(e,d)=>e?send(r,404,'text/plain','Not found'):send(r,200,p.endsWith('.css')?'text/css':p.endsWith('.js')?'application/javascript':'text/html',d))}catch(e){let conflict=e.code==='23503'||e.code==='23001';send(r,conflict?409:500,'application/json',JSON.stringify({error:conflict&&q.method==='DELETE'&&u.pathname.startsWith('/api/corpora/')?'This corpus is used by a saved analysis. Delete the analysis first.':conflict?'A saved record still depends on this item.':e.message}))}}).listen(process.env.PORT||3000);