import pg from 'pg';const {Pool}=pg;const pool=new Pool({connectionString:process.env.DATABASE_URL});
const q=async s=>(await pool.query(s)).rows;
try{
const counts=(await q("SELECT (SELECT count(*) FROM projects)::int projects,(SELECT count(*) FROM searches)::int searches,(SELECT count(*) FROM corpora)::int corpora,(SELECT count(*) FROM analyses)::int analyses"))[0];
const projects=await q("SELECT p.id,p.name,p.created_at,p.updated_at,(SELECT count(*) FROM searches s WHERE s.project_id=p.id)::int searches,(SELECT count(*) FROM corpora c WHERE c.project_id=p.id)::int corpora,(SELECT count(*) FROM analyses a WHERE a.project_id=p.id)::int analyses FROM projects p ORDER BY p.created_at");
const searches=await q("SELECT id,project_id,name,result_count,jsonb_array_length(COALESCE(result_snapshot->'works','[]'::jsonb)) snapshot_count,created_at,updated_at FROM searches ORDER BY created_at");
const corpora=await q("SELECT id,project_id,search_id,name,version,jsonb_array_length(works) work_count,created_at,updated_at FROM corpora ORDER BY created_at");
const analyses=await q("SELECT id,project_id,corpus_id,name,jsonb_array_length(corpus) corpus_count,COALESCE(jsonb_array_length(network->'nodes'),0) node_count,COALESCE(jsonb_array_length(network->'edges'),0) edge_count,parameters,network->'stats' stats,(search_snapshot<>'{}'::jsonb) has_search_snapshot,(cited_works<>'{}'::jsonb) has_cited_works,(view_state<>'{}'::jsonb) has_view_state,created_at,updated_at FROM analyses ORDER BY created_at");
const integrity=(await q("SELECT (SELECT count(*) FROM searches s LEFT JOIN projects p ON p.id=s.project_id WHERE p.id IS NULL)::int orphan_searches,(SELECT count(*) FROM corpora c LEFT JOIN projects p ON p.id=c.project_id WHERE p.id IS NULL)::int orphan_corpora,(SELECT count(*) FROM analyses a LEFT JOIN projects p ON p.id=a.project_id WHERE p.id IS NULL)::int orphan_analyses,(SELECT count(*) FROM corpora c LEFT JOIN searches s ON s.id=c.search_id WHERE c.search_id IS NOT NULL AND s.id IS NULL)::int broken_corpus_search_links,(SELECT count(*) FROM analyses a LEFT JOIN corpora c ON c.id=a.corpus_id WHERE a.corpus_id IS NOT NULL AND c.id IS NULL)::int broken_analysis_corpus_links"))[0];
console.log("=== BIBLIOMAP_DB_AUDIT_START ===");console.log(JSON.stringify({counts,projects,searches,corpora,analyses,integrity},null,2));console.log("=== BIBLIOMAP_DB_AUDIT_END ===");
}catch(e){console.error("BIBLIOMAP_DB_AUDIT_ERROR",e.message);process.exitCode=1}finally{await pool.end()}